name: couclient
description: 'Children of Ur :: Webclient'
dependencies:
  browser: any
  dnd: '^0.3.0'
  firebase: '>=0.5.0 <0.6.0'
  gorgon: any
  intl: any
  jsonx: "2.0.0"
  xml: "^2.4.0"
  libld:
    git:
      ref: master
      url: git://github.com/ChildrenOfUr/libld.git
  paper_elements: ">=0.7.0 <0.8.0"
  polymer: '>=0.16.1 < 0.17.0'
  transmit:
        git:
          ref: master
          url: git://github.com/ChildrenOfUr/transmit.git
  scproxy:
    git:
      ref: master
      url: git://github.com/ChildrenOfUr/scproxy.git
  slack: "1.2.1+1"
  cou_auction_house:
    git:
      ref: master
      url: git://github.com/ChildrenOfUr/auction_house.git
  cou_toolkit:
      git:
        ref: master
        url: git://github.com/ChildrenOfUr/cou_toolkit.git
  cou_login:
      git:
        ref: dev
        url: https://github.com/ChildrenOfUr/cou_login.git
  coufeedback:
      git:
        ref: userfeedback
        url: git://github.com/ChildrenOfUr/cou-issues.git
  stagexl: "^0.12.0"
  browser_detect: "^1.0.3"
  coUemoticons:
      git: git://github.com/ChildrenOfUr/emoticons.git

transformers:
- couclient/transformers/configs_transformer
- polymer:
    entry_points:
    - web/index.html
