name: core_elements
version: 0.7.0
author: Polymer.dart Authors <web-ui-dev@dartlang.org>
description: Polymer core-elements for Dart
homepage: https://www.dartlang.org/polymer/
dependencies:
  custom_element_apigen: ">=0.1.5 <0.1.7"
  polymer: ">=0.16.0 <0.17.0"
  quiver: ">=0.17.0 <0.22.0"
  web_components: ">=0.9.0 <0.12.0"
dev_dependencies:
  html5lib: ">=0.11.0 <0.13.0"
  path: ">=1.0.0 <2.0.0"
  yaml: ">=1.0.0 <3.0.0"
  unittest: ">=0.11.0+2 <0.12.0"
  matcher: ">=0.10.1+1 <0.12.0"
environment:
  sdk: '>=1.6.0 <2.0.0'
transformers:
- polymer:
    lint:
      exclude:
        - lib/src/
    entry_points:
#    - test/core_ajax_dart_test.html
#    - test/core_ajax_dart_progress_test.html
#    - test/core_animated_pages_test.html
#    - test/core_collapse_test.html
#    - test/core_dropdown_test.html
#    - test/core_dropdown_menu_test.html
#    - test/core_dropdown_menu_a11y_test.html
#    - test/core_input_test.html
#    - test/core_input_basic_test.html
#    - test/core_input_a11y_test.html
#    - test/core_list_dart_basic_test.html
#    - test/core_localstorage_dart_test.html
#    - test/core_localstorage_dart_raw_test.html
#    - test/core_localstorage_dart_value_binding_test.html
#    - test/core_media_query_test.html
#    - test/core_media_query_dialog_test.html
#    - test/core_menu_button_test.html
#    - test/core_overlay_positioning_test.html
#    - test/core_range_test.html
#    - test/core_selection_test.html
#    - test/core_selection_multi_test.html
#    - test/core_selection_multi_test.html
#    - test/core_selector_activate_event_test.html
#    - test/core_selector_basic_test.html
#    - test/core_selector_content_test.html
#    - test/core_selector_multi_test.html
#    - test/core_shared_lib_test.html
#    - test/core_toolbar_test.html
- $dart2js:
    $include: "**/*.polymer.bootstrap.dart"
